// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDs-TMV3qcHFIlqA49lZkYpGL2XQx2IzE4',
    appId: '1:1096030685716:web:c8c188735a43c73bee7501',
    messagingSenderId: '1096030685716',
    projectId: 'habit-tracker-7bb13',
    authDomain: 'habit-tracker-7bb13.firebaseapp.com',
    storageBucket: 'habit-tracker-7bb13.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_MK6V0RV7wdKONBEsX5nSX6ovvMRI1fY',
    appId: '1:1096030685716:android:26ea1c8658fa74c5ee7501',
    messagingSenderId: '1096030685716',
    projectId: 'habit-tracker-7bb13',
    storageBucket: 'habit-tracker-7bb13.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7GDTvoozJWCCN2vhckHs7tWEmV111C3Y',
    appId: '1:1096030685716:ios:cb727760fb6adf26ee7501',
    messagingSenderId: '1096030685716',
    projectId: 'habit-tracker-7bb13',
    storageBucket: 'habit-tracker-7bb13.appspot.com',
    iosClientId: '1096030685716-ue7bgrmdsm8pb8ovbb8hfvmqr3o3abpp.apps.googleusercontent.com',
    iosBundleId: 'com.example.habitTracer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7GDTvoozJWCCN2vhckHs7tWEmV111C3Y',
    appId: '1:1096030685716:ios:cb727760fb6adf26ee7501',
    messagingSenderId: '1096030685716',
    projectId: 'habit-tracker-7bb13',
    storageBucket: 'habit-tracker-7bb13.appspot.com',
    iosClientId: '1096030685716-ue7bgrmdsm8pb8ovbb8hfvmqr3o3abpp.apps.googleusercontent.com',
    iosBundleId: 'com.example.habitTracer',
  );
}
